# Generated by Django 4.2.9 on 2024-02-01 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaperApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
