# Generated by Django 4.2.9 on 2024-02-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaperApp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
